/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliothecaire;

import Controller.ServicesAdmin;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 

/**
 *
 * @author HP
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    DefaultTableModel modelConsul,modelRese;
    public FenetrePrincipale() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelConsul = new DefaultTableModel();
        modelRese = new DefaultTableModel();
    
        InitialisationTableConsul();
        InitialisationTableReser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        ToolBar_AjouterLivre = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        ToolBar_ModifierLivre = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        ToolBar_SupprimerLivre = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        ToolBar_AjouterAdh = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        ToolBar_SuppAdh = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        Bt_quitter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsultation = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Bt_Rafraichir = new javax.swing.JButton();
        Bt_rajouter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_reservation = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtBoxReservation = new javax.swing.JTextField();
        Bt_valider = new javax.swing.JButton();
        Bt_rafraichirReserv = new javax.swing.JButton();
        Bt_ListeLivresReserves = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtMenuQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FENETRE GESTION");

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        ToolBar_AjouterLivre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToolBar_AjouterLivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plus Math_24px.png"))); // NOI18N
        ToolBar_AjouterLivre.setText("Ajouter livre");
        ToolBar_AjouterLivre.setFocusable(false);
        ToolBar_AjouterLivre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolBar_AjouterLivre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_AjouterLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolBar_AjouterLivreActionPerformed(evt);
            }
        });
        jToolBar1.add(ToolBar_AjouterLivre);
        jToolBar1.add(jSeparator1);

        ToolBar_ModifierLivre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToolBar_ModifierLivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_32px_1.png"))); // NOI18N
        ToolBar_ModifierLivre.setText("Modifier livre");
        ToolBar_ModifierLivre.setFocusable(false);
        ToolBar_ModifierLivre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolBar_ModifierLivre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_ModifierLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolBar_ModifierLivreActionPerformed(evt);
            }
        });
        jToolBar1.add(ToolBar_ModifierLivre);
        jToolBar1.add(jSeparator2);

        ToolBar_SupprimerLivre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToolBar_SupprimerLivre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete_32px.png"))); // NOI18N
        ToolBar_SupprimerLivre.setText("Supprimer livre");
        ToolBar_SupprimerLivre.setFocusable(false);
        ToolBar_SupprimerLivre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolBar_SupprimerLivre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_SupprimerLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolBar_SupprimerLivreActionPerformed(evt);
            }
        });
        jToolBar1.add(ToolBar_SupprimerLivre);
        jToolBar1.add(jSeparator3);

        ToolBar_AjouterAdh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToolBar_AjouterAdh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add User Male_32px.png"))); // NOI18N
        ToolBar_AjouterAdh.setText("Ajouter Adhérent");
        ToolBar_AjouterAdh.setFocusable(false);
        ToolBar_AjouterAdh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolBar_AjouterAdh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_AjouterAdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolBar_AjouterAdhActionPerformed(evt);
            }
        });
        jToolBar1.add(ToolBar_AjouterAdh);
        jToolBar1.add(jSeparator4);

        ToolBar_SuppAdh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToolBar_SuppAdh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Remove User Male_32px.png"))); // NOI18N
        ToolBar_SuppAdh.setText("Supprimer un Adhérent");
        ToolBar_SuppAdh.setFocusable(false);
        ToolBar_SuppAdh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ToolBar_SuppAdh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar_SuppAdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolBar_SuppAdhActionPerformed(evt);
            }
        });
        jToolBar1.add(ToolBar_SuppAdh);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator6);

        Bt_quitter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close Window_32px.png"))); // NOI18N
        Bt_quitter.setText("Quitter");
        Bt_quitter.setFocusable(false);
        Bt_quitter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bt_quitter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bt_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_quitterActionPerformed(evt);
            }
        });
        jToolBar1.add(Bt_quitter);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TableConsultation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TableConsultation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableConsultation);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Consultation");

        Bt_Rafraichir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Rafraichir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Restart_32px.png"))); // NOI18N
        Bt_Rafraichir.setText("Rafraîchir");
        Bt_Rafraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_RafraichirActionPerformed(evt);
            }
        });

        Bt_rajouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_rajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add File_32px.png"))); // NOI18N
        Bt_rajouter.setText("Rajouter");
        Bt_rajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Bt_Rafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bt_rajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_rajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Rafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Centre demande de réservation");

        Table_reservation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_reservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Table_reservation);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Confirmation réservation");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Référence :");

        TxtBoxReservation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtBoxReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBoxReservationActionPerformed(evt);
            }
        });

        Bt_valider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ok_32px.png"))); // NOI18N
        Bt_valider.setText("Valider");
        Bt_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_validerActionPerformed(evt);
            }
        });

        Bt_rafraichirReserv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_rafraichirReserv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recurring Appointment_32px.png"))); // NOI18N
        Bt_rafraichirReserv.setText("Rafraîchir");
        Bt_rafraichirReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_rafraichirReservActionPerformed(evt);
            }
        });

        Bt_ListeLivresReserves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_ListeLivresReserves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingredients List_32px.png"))); // NOI18N
        Bt_ListeLivresReserves.setText("Liste des livres réservés");
        Bt_ListeLivresReserves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ListeLivresReservesActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtBoxReservation))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Bt_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Bt_rafraichirReserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_ListeLivresReserves, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bt_rafraichirReserv)
                            .addComponent(Bt_ListeLivresReserves))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtBoxReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bt_valider)
                .addGap(1, 1, 1))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BIBLIOTHEQUE UFR-MI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenu1.setText("Fichier");

        BtMenuQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close Window_32px.png"))); // NOI18N
        BtMenuQuitter.setText("Quitter");
        BtMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMenuQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(BtMenuQuitter);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolBar_AjouterAdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolBar_AjouterAdhActionPerformed
        AjouterAdherent fen = new AjouterAdherent();
        fen.setVisible(true);
    }//GEN-LAST:event_ToolBar_AjouterAdhActionPerformed

    private void TxtBoxReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBoxReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBoxReservationActionPerformed

    private void ToolBar_AjouterLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolBar_AjouterLivreActionPerformed
        AjouterLivre fen = new AjouterLivre();
        fen.setVisible(true);
    }//GEN-LAST:event_ToolBar_AjouterLivreActionPerformed

    private void Bt_RafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_RafraichirActionPerformed
        InitialisationTableConsul();
    }//GEN-LAST:event_Bt_RafraichirActionPerformed

    private void ToolBar_ModifierLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolBar_ModifierLivreActionPerformed
        //On récupère la réf du livre   modelConsul.getValueAt(0, 0).toString()
        String ref = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 0).toString();
        String titre = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 1).toString();
        String genre = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 2).toString();
        String edition = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 3).toString();
        String nom = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 4).toString();
        String prenom = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 5).toString();
        ModifierLivre fen = new ModifierLivre(ref,titre,genre,edition,nom,prenom);
        fen.setVisible(true);
        
    }//GEN-LAST:event_ToolBar_ModifierLivreActionPerformed

    private void ToolBar_SupprimerLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolBar_SupprimerLivreActionPerformed
        SupprimerLivre fen = new SupprimerLivre();
        fen.setVisible(true);
    }//GEN-LAST:event_ToolBar_SupprimerLivreActionPerformed

    private void ToolBar_SuppAdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolBar_SuppAdhActionPerformed
        SupprimerAdherent fen = new SupprimerAdherent();
        fen.setVisible(true);
    }//GEN-LAST:event_ToolBar_SuppAdhActionPerformed

    private void Bt_rajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rajouterActionPerformed
        String ref = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 0).toString();
        String titre = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 1).toString();
        String genre = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 2).toString();
        String edition = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 3).toString();
        String nom = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 4).toString();
        String prenom = modelConsul.getValueAt(TableConsultation.getSelectedRow(), 5).toString();
        RajouterLivre fen = new RajouterLivre(ref,titre,genre,edition,nom,prenom);
        fen.setVisible(true);
    }//GEN-LAST:event_Bt_rajouterActionPerformed

    private void Bt_rafraichirReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_rafraichirReservActionPerformed
        InitialisationTableReser();
    }//GEN-LAST:event_Bt_rafraichirReservActionPerformed

    private void Bt_ListeLivresReservesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ListeLivresReservesActionPerformed
        try { 
            ServicesAdmin stub = (ServicesAdmin) Naming.lookup("rmi://127.0.1.1:1099/80");
            modelRese = stub.Consultation_livreReserves();
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
           JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        Table_reservation.setModel(modelRese);
    }//GEN-LAST:event_Bt_ListeLivresReservesActionPerformed

    private void Bt_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_validerActionPerformed
        try { 
            ServicesAdmin stub = (ServicesAdmin) Naming.lookup("rmi://127.0.1.1:1099/80");
            stub.ValiderReservation(TxtBoxReservation.getText());
            JOptionPane.showMessageDialog(null,"Livre réservé avec succès","Réservation de livre",JOptionPane.INFORMATION_MESSAGE);  
            InitialisationTableReser();
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
           JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Bt_validerActionPerformed

    private void Bt_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_quitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Bt_quitterActionPerformed

    private void BtMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMenuQuitterActionPerformed
        // TODO add your handling code here:*
        System.exit(0);
    }//GEN-LAST:event_BtMenuQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtMenuQuitter;
    private javax.swing.JButton Bt_ListeLivresReserves;
    private javax.swing.JButton Bt_Rafraichir;
    private javax.swing.JButton Bt_quitter;
    private javax.swing.JButton Bt_rafraichirReserv;
    private javax.swing.JButton Bt_rajouter;
    private javax.swing.JButton Bt_valider;
    private javax.swing.JTable TableConsultation;
    private javax.swing.JTable Table_reservation;
    private javax.swing.JButton ToolBar_AjouterAdh;
    private javax.swing.JButton ToolBar_AjouterLivre;
    private javax.swing.JButton ToolBar_ModifierLivre;
    private javax.swing.JButton ToolBar_SuppAdh;
    private javax.swing.JButton ToolBar_SupprimerLivre;
    private javax.swing.JTextField TxtBoxReservation;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public void InitialisationTableConsul(){
        try { 
            ServicesAdmin stub = (ServicesAdmin) Naming.lookup("rmi://127.0.1.1:1099/80");
            modelConsul = stub.Consultation_livres();
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
           JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        TableConsultation.setModel(modelConsul);
    }
    
    public void InitialisationTableReser(){
        try { 
            ServicesAdmin stub = (ServicesAdmin) Naming.lookup("rmi://127.0.1.1:1099/80");
            modelRese = stub.Consultation_livreReservation();
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        } catch (RemoteException ex) {
           JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur"+ex,"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        Table_reservation.setModel(modelRese);
    }

}
